import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/context/AuthContext";
import { useEffect } from "react";
import { Providers } from "@/providers";
import theme from "@/theme";
import { ColorModeScript } from "@chakra-ui/react";
import Script from "next/script";
import { Head } from "next/document";
import { CustomerFeedback } from "../components/global/CustomerFeedback";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rico | Apply to jobs with one click",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Provider>
          <Providers>{children}</Providers>
        </Provider>
        {/* <CustomerFeedback /> */}
      </body>
    </html>
  );
}
